Repository jekyll/minima, pull requests merged in 2018-10, with the labels that each got.

#284 README update re Disqus
  README.md
Labels: documentation

#290 Update URL on #158
  README.md
Labels: documentation

#289 Hide nav toggle if nav is empty.
  _includes/header.html
Labels: ux

#292 Add YouTube channel to social
  README.md
  _config.yml
  _includes/social.html
Labels: enhancement
