Repository jekyll/minima, pull requests merged in 2020-01, with the labels that each got.

#373 Docs: remove Google+
  README.md
Labels: documentation

#435 Use "em" unit in relative-font-size mixin
  _sass/minima/initialize.scss
Labels: fix

#436 Use "rem" unit in relative-font-size mixin
  History.markdown
  _sass/minima/_base.scss
  _sass/minima/initialize.scss
Labels: fix

#437 Assign static value to variable outside forloop
  _layouts/home.html
Labels: fix, optimization :zap:

#441 Add font-size styles for elements h5 and h6
  _posts/2016-05-20-this-post-demonstrates-post-content-styles.md
  _sass/minima/_layout.scss
Labels: fix

#438 Update README section on adding favicons to site
  README.md
Labels: documentation

#443 Add stackoverflow to social media list
  README.md
  _includes/social.html
Labels: duplicate, social-media-support

#410 Add social support for dev.to
  _config.yml
  _includes/social.html
  assets/minima-social-icons.svg
Labels: social-media-support

#352 Add GitLab to social
  README.md
  _config.yml
  _includes/social.html
  assets/minima-social-icons.svg
Labels: social-media-support

#448 Re-implement site footer markup and styles
  _includes/footer.html
  _sass/minima/_layout.scss
Labels: fix

#449 Improve readability of post titles with diacritics
  _sass/minima/_layout.scss
Labels: fix

#450 Support pagination through posts in home layout
  _layouts/home.html
  _sass/minima/_layout.scss
Labels: enhancement
